
const data = {
    products: [
        {
            _id: '1',
            name: 'Peach-Coloured Printed Maxi Top',
            category: 'Tops',
            image: 'images/product-1.1.jpg',
            price: 1200,
            brand: 'Miss Chase',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '2',
            name: 'Yellow A-Line Mini Dress',
            category: 'Dresses',
            image: 'images/product-2.1.jpg',
            price: 679,
            brand: 'Berrylush',
            rating: 3.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '3',
            name: 'Wide Leg High-Rise Jeans',
            category: 'Jeans',
            image: 'images/product-3.1.jpg',
            price: 989,
            brand: 'SASSAFRAS',
            rating: 4.0,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '4',
            name: 'Green PU Structured Bag',
            category: 'purses',
            image: 'images/product-4.1.jpg',
            price: 2519,
            brand: 'Allen Solly',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '5',
            name: 'Solid Regular Top',
            category: 'Tops',
            image: 'images/product-5.1.jpg',
            price: 399,
            brand: 'her by invictus',
            rating: 3.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '6',
            name: 'Printed Maxi Dress',
            category: 'Dresses',
            image: 'images/product-9.1.jpg',
            price: 1024,
            brand: 'Sangria',
            rating: 4.0,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '7',
            name: 'Women Straight Fit Jeans',
            category: 'Jeans',
            image: 'images/product-13.1.jpg',
            price: 1299,
            brand: 'URBANIC',
            rating: 5.0,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '8',
            name: 'Solid Sling Bag',
            category: 'purses',
            image: 'images/product-17.1.jpg',
            price: 999,
            brand: 'KLEIO',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
    ],
};
export default data;